services:
  react-app:
    image: node:20
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
